name: deepbee
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - keras=2.3
  - numpy=1.18
  - scipy=1.4
  - click
  - pytest
  - pip:
    - opencv-python==3.4.2.16
    - tqdm==4.42
